[package]
name = "qemu-command-builder"
version = "11.1.0-1"
edition = "2024"
authors = ["Adam Flott <adam@adamflott.com>"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/adamflott/qemu-command-builder"
keywords = ["qemu"]
description = "Type safe command line builder for qemu"
homepage = "https://github.com/adamflott/qemu-command-builder"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
annotate-snippets = "0.12.16"
bon = "3.9.1"
chrono = {  version = "0.4.44", features = [ "arbitrary"] }
ipnet = "2.12.0"
newtype-uuid = { version = "1.3.2", features = ["proptest1", "v4"]}
proptest = "1.11.0"
proptest-derive = "0.8.0"
shellish_parse = "2.2.0"
winnow = "1.0.2"

[dev-dependencies]
pretty_assertions = "1.4.1"

[[bin]]
name = "parse_qemu_command"
path = "src/bin/parse_qemu_command.rs"